### ISSUE TITLE
Fill a form automatically by nodes

### ISSUE THREAD

**Issue by oadominguez** [niklasb/dryscrape#27]
Dear Niklas:
Is there a way to retrieve and full a form automatically?

In your example use:
q = sess.at_xpath('//*[@name="q"]')

This is when you know the structure of the form, 
I try this:
text = sess.at_xpath('//*[@type="text"]')
but isn't succesful, what i want is fill a form automatically, without know the previous structure, extracting node by node with their type (text, checkbox, button, etc)

I hope i was explicit.

Thank you, and regards!

**Comment by niklasb** [comment]
Well `//*[@type="text"]` is a valid query to select DOM elements that have their `type` attribute 
set to `"text"`. So if that's what you want, I don't see why it would not work. I guess you have to be a bit more specific if you want more detailled help :)
