### ISSUE TITLE
python3 support  issure

### ISSUE THREAD

**Issue by a358003542** [niklasb/dryscrape#28]
1.  the dryscape __init__.py  
line 1 from .session import *
recommend  not use the relative represitation
    from dryscrape.session import *
    import dryscrape.driver

2. the dryscape session.py
line 1 import urlparse
changed to 
from urllib.parse import urlparse,urljoin

and the line 34
      return urlparse.urljoin(self.base_url, url)

changed to 
       return urljoin(self.base_url, url)

3. the dryscrape mixins.py
line 100:     raise WaitTimeoutError , "wait_for timed out"
changed to 
    raise WaitTimeoutError("wait_for timed out")

4.
this is webkit_server issue for python3 

https://github.com/niklasb/webkit-server/issues/15

now it can run under python3 .

**Comment by niklasb** [comment]
This should be resolved via https://github.com/niklasb/webkit-server/commit/574b1d35ff66c8669f400de21d193d5887bf8ec3 and https://github.com/niklasb/dryscrape/commit/214446f5f89a29c8a600034a7b2f8af5a3164cf1
