### ISSUE TITLE
Popups

### ISSUE THREAD

**Issue by jeanrigoud** [niklasb/dryscrape#29]
Anyone knows how to handle popups ?

Thanks

**Comment by niklasb** [comment]
There is no explicit support for these and none is planned. However there is always the option to hook the Javascript functions that can be used to open a popup.

**Comment by jeanrigoud** [comment]
Sorry for not being clear enough. How can I get the content of a popup I have opened using the click function ?
I haven't found any documentation describing how to do this.
Thanks

**Comment by niklasb** [comment]
webkit-server doesn't support multiple tabs or windows, so I think you are out of luck.

**Comment by jeanrigoud** [comment]
Thanks for the quick answer !

**Comment by jeanrigoud** [comment]
Is it possible to load the popup manually even if it is a POST request ?

Thanks

**Comment by niklasb** [comment]
You could try loading the markup using some other mechanism (i.e. using the `requests` library) and then use `set_html` to transfer it to dryscrape.
