### ISSUE TITLE
how to scrape inside objects?

### ISSUE THREAD

**Issue by carlzoo** [niklasb/dryscrape#32]
How can I use this library in objects?
I found that whenever I try to use dryscrape inside xvfbwrapper and there is two instances, a connection refused error occurs.

Example - 1 object
```Python
#!/usr/bin/env python
import dryscrape
from xvfbwrapper import Xvfb

class SomeObj(object):
	def __init__(self):
		self.url="http://www.google.com/"
		self.timeout=20

	def fetch_page(self):
		with Xvfb() as xfvb:
			sess = dryscrape.Session(base_url = self.url)
			sess.visit('/')
			print sess.body()

a=SomeObj()
a.fetch_page()
```
(Outputs html, works OK)

Example 2-two objects
```Python
#!/usr/bin/env python
import dryscrape
from xvfbwrapper import Xvfb

class SomeObj(object):
	def __init__(self):
		self.url="http://www.google.com/"
		self.timeout=20

	def fetch_page(self):
		with Xvfb() as xfvb:
			sess = dryscrape.Session(base_url = self.url)
			sess.visit('/')
			print sess.body()

a=SomeObj()
b=SomeObj()
a.fetch_page()
b.fetch_page()
```
(Outputs html)
```shell
Traceback (most recent call last):
  File "objecttest.py", line 19, in <module>
    b.fetch_page()
  File "objecttest.py", line 12, in fetch_page
    sess = dryscrape.Session(base_url = self.url)
  File "/home/carl/workspace/env2/lib/python2.7/site-packages/dryscrape/session.py", line 18, in __init__
    self.driver = driver or DefaultDriver()
  File "/home/carl/workspace/env2/lib/python2.7/site-packages/dryscrape/driver/webkit.py", line 30, in __init__
    super(Driver, self).__init__(**kw)
  File "/home/carl/workspace/env2/lib/python2.7/site-packages/webkit_server.py", line 225, in __init__
    self.conn = connection or ServerConnection()
  File "/home/carl/workspace/env2/lib/python2.7/site-packages/webkit_server.py", line 444, in __init__
    self._sock = (server or get_default_server()).connect()
  File "/home/carl/workspace/env2/lib/python2.7/site-packages/webkit_server.py", line 414, in connect
    sock.connect(("127.0.0.1", self._port))
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
```

How can I solve this issue? Do I need to use subprocess and have the fetch_page function in a seperate file? Thanks.

**Comment by niklasb** [comment]
It should work within the same process. I just tried without xvfbwrapper and it did work. I will try later with xvfb to see if I can reproduce this.

**Comment by niklasb** [comment]
Sorry I didn't get back to you about this earlier. Have you tried wrapping the whole thing in Xvfb instead of using two different instances? Like 

    #!/usr/bin/env python
    import dryscrape
    from xvfbwrapper import Xvfb

    class SomeObj(object):
        def __init__(self):
            self.url="http://www.google.com/"
            self.timeout=20

        def fetch_page(self):
            sess = dryscrape.Session(base_url = self.url)
            sess.visit('/')
            print sess.body()

    with Xvfb() as xfvb:
        a=SomeObj()
        b=SomeObj()
        a.fetch_page()
        b.fetch_page()

**Comment by carlzoo** [comment]
Hello,
Thanks for the reply. The second method works without any issues.

**Comment by niklasb** [comment]
There is a small helper function in dryscrape 1.0 that can be used to start the framebuffer once: Just call `dryscrape.start_xvbf()` at the beginning of the script.

**Comment by Nebucatnetzer** [comment]
Just for other readers, the comment above contains a typo.
It should be `dryscrape.start_xvfb()` not `dryscrape.start_xvbf()`
