### ISSUE TITLE
NoX11Error on OS X Yosemite

### ISSUE THREAD

**Issue by johngu** [niklasb/dryscrape#33]
Hello,

I'm getting a NoX11Error when attempting to use dryscrape on X11. I'm using python 2.7 (with anaconda), and I have XQuartz installed and running. The installations all went fine (Qt, pip, webserver-kit, etc.).  Any help would be appreciated. 

Johns-MacBook-Pro:dryscrape johngu$ echo $DISPLAY
/private/tmp/com.apple.launchd.57RQ2D0Hcg/org.macosforge.xquartz:0

/Users/john/anaconda/lib/python2.7/site-packages/webkit_server.pyc in get_default_server()
    429   global default_server
    430   if not default_server:
--> 431     default_server = Server()
    432   return default_server
    433 

/Users/john/anaconda/lib/python2.7/site-packages/webkit_server.pyc in __init__(self, binary)
    407       self._port = int(re.search("port: (\d+)", output).group(1))
    408     except AttributeError:
--> 409       raise NoX11Error, "Cannot connect to X. You can try running with xvfb-run."
    410 
    411     # on program termination, kill the server instance

**Comment by niklasb** [comment]
Have you tried not using XQuartz at all, i.e. `export DISPLAY=`? I just installed it on my Mac without problems, and it seems to work as is, without an X server running

**Comment by niklasb** [comment]
It might also be useful to see the full output of webkit-server. Can you try running `/Library/Python/2.7/site-packages/webkit_server`?

**Comment by johngu** [comment]
I'm running an install of Anaconda python (http://continuum.io/downloads),
so the location of my webkit_server is a bit different:

Johns-MacBook-Pro:site-packages johngu$ pwd

/Users/john/anaconda/lib/python2.7/site-packages

Johns-MacBook-Pro:site-packages johngu$ ./webkit_server

dyld: Library not loaded: libQtWebKit.4.dylib

  Referenced from:
/Users/john/anaconda/lib/python2.7/site-packages/./webkit_server

  Reason: image not found

Trace/BPT trap: 5

Johns-MacBook-Pro:~ johngu$ find . -name libQtWebKit.4.dylib

./anaconda/envs/python3/lib/libQtWebKit.4.dylib

./anaconda/lib/libQtWebKit.4.dylib

./anaconda/pkgs/qt-4.8.6-0/lib/libQtWebKit.4.dylib
I think did this: export
DYLD_FALLBACK_LIBRARY_PATH=/Users/johngu/anaconda/lib

After that I was able to operate the program fine.  I think it's just a
function of my using anaconda and the webkit_server not knowing where to
look for the libQt dylib's.

**Comment by niklasb** [comment]
thanks for letting me know. I should probably make the error message more specific, right now it just assumes that webkit_server failed to due a missing X connection if it doesn't run properly...
