### ISSUE TITLE
Speeding up parsing with threads

### ISSUE THREAD

**Issue by andr3w321** [niklasb/dryscrape#39]
I'm trying to parse a series of events, but doing it serially is taking upwards of a minute since there are so many parts of each event to parse.  I'd like to try and speed it up with threading, the only problem is apparently webkit doesn't like that.  See https://github.com/niklasb/dryscrape/issues/9

What's the best way to go about it?  I can't call node.at_css() on objects in threads.  Is it best to save the html using `html_body = session.body().encode('ascii', 'ignore')` and then use another parser like https://pythonhosted.org/cssselect/ or is there a better way using dryscrape?

Header
```
def parse_event(event):
    print event.at_css('.name')
    // more parsing
    return

import dryscrape
import threading
url = "https://example.com"
dryscrape.start_xvfb()
session = dryscrape.Session()
session.visit(url)
events = session.css('.event')
```

Serially works fine
```
for event in events:
    parse_event(event)
```

With threads fails
```
threads = []
for event in events:
    t = threading.Thread(target=parse_event, args=(event, ))
    threads.append(t)
    t.start()
```

**Comment by niklasb** [comment]
Hi! Parsing the HTML manually would be a good way to do it. You can use `session.document()` to get a parsed lxml.html document, which you can query with XPath. 
You can also have multiple sessions, but that seems somewhat wasteful, depending on how many threads you have.

**Comment by andr3w321** [comment]
Thanks.  I was able to get this sped up quite a bit (from ~70 secs to ~25 secs) by switching to doing the parsing on session.document() instead of on the session so I ditched the threading and didn't even need it.  I'm not sure why lxml is so much faster than dryscrape, but for anyone looking for speed enhancements I'd suggest not using dryscrapes parsing functions.  The biggest issue I had with code refactoring was figuring out how to change all my `session.at_css('class-name')` selectors.  Here's a sample of the refactored code.

```
doc = session.document()
events = doc.cssselect('.event')
for event in events:
    name = event.cssselect('.name')
    if name:
        print name[0].text_content()
```

**Comment by niklasb** [comment]
Just to clarify: session.document() basically just extracts the HTML and parses it, so it represents a snapshot, while the dryscrape selectors work on the live DOM of the web page (which can change). For the latter interaction with the webkit-server is necessary, thus it is slower.
