### ISSUE TITLE
Scrape infinity scrolling pages

### ISSUE THREAD

**Issue by arvindr21** [niklasb/dryscrape#40]
Hello,

Thanks for the library. 

I am trying to extract content from pages that are scrolling infinity. Can you please let me know how I can achieve this? I did not find an API method to scroll after I have reached the end of a page/section. 

Thanks.

**Comment by niklasb** [comment]
Sometimes it is enough to just raise the viewport size to the designated length of the page. If the page does not react to this, you can try scrolling in Javascript, using the [`exec_script`](https://dryscrape.readthedocs.org/en/latest/apidoc.html#webkit_server.Client.exec_script) method.

**Comment by arvindr21** [comment]
Ok. Thanks, let me try that.
