### ISSUE TITLE
most recent version on pip?

### ISSUE THREAD

**Issue by SwedishBotMafia** [niklasb/dryscrape#48]
I found differences in what was in xvfb.py here on github and what was on pypi. Any chance on getting the new version on pypi as well?

**Comment by niklasb** [comment]
The upstream version should be almost exactly the same as the current master branch, if I'm not mistaken. The only difference indeed is that there is a `dryscrape.xvfb.stop_xvfb()` function in master, which is not present in the PyPI repositories. I'm not sure it warrants a version bump.

**Comment by SwedishBotMafia** [comment]
Gotchya, yeah just the function I was trying to use and could not figure out for the life of me why it wasn't working until I compared the github to the contents of the pypi package.

**Comment by niklasb** [comment]
Ok that is indeed unfortunate. Maybe I will release a minor version bump with this change, but until then you can just use the module from `master`.
