### ISSUE TITLE
google search results right panel is not in session source file 

### ISSUE THREAD

**Issue by deter3** [niklasb/dryscrape#49]
running the code below : 

search_term = 'tokyo skytree'
sess = dryscrape.Session(base_url = 'https://www.google.co.jp')
sess.set_attribute('auto_load_images', True)
sess.visit('/')
q = sess.at_xpath('//*[@name="q"]')
q.set(search_term)
q.form().submit()

print sess.source()

There is a google right knowledge panel in the rendered png file (see below ) , but can not find in the session source file . 

How can I fix it  ? Thanks a lot 

Richard 

![google](https://cloud.githubusercontent.com/assets/11637246/13821088/8482d954-ebe3-11e5-9e91-b35a794c63a7.png)

**Comment by niklasb** [comment]
Compare [`Session#source`](https://dryscrape.readthedocs.org/en/latest/apidoc.html#webkit_server.Client.source) and [`Session#body`](https://dryscrape.readthedocs.org/en/latest/apidoc.html#webkit_server.Client.body). The letter is probably what you want.

**Comment by deter3** [comment]
Thanks a lot for the prompt reply .  You are right , session#body is the one I am looking for .  

The strangest thing is webkit_server and PhantomJS might has different xpath class from firefox and chrome for same  elements .
