### ISSUE TITLE
dryscrape console.log

### ISSUE THREAD

**Issue by JulienSoda** [niklasb/dryscrape#64]
Hello, congratulation for dryscrape.

Is it possible, with dryscrape, to get console.log(), like selenium:
for entry in driver.get_log('browser'):
    print(entry)

Best regards

**Comment by JulienSoda** [comment]
I Try:

hello = sess.exec_script('console.log("Hello World1")')
print(hello)
hello2 = sess.exec_script('document.write("Hello World2");')
print(hello2)

But no result:
None
None

**Comment by JulienSoda** [comment]
succeded:

hello4 = sess.eval_script("function hello4(){ return 10;};hello4();")
print(hello4)

the script return: 10

**Comment by niklasb** [comment]
This is not implemented. I would be happy to consider accepting this as a pull request.
