### ISSUE TITLE
Windows 10 Support

### ISSUE THREAD

**Issue by willbishop** [niklasb/dryscrape#67]
All my code runs on an Ubuntu based OS, however I do the majority of my prototyping on a Windows machine. I am currently unable to use said Windows machine, but I am wondering what the kind of support is like if all I am doing it fetching a webpage with dryscrape and then parsing with `BeautifulSoup4`. Can I expect problems?

**Comment by niklasb** [comment]
Windows 10 is not officially supported. Feel free to try it out and let me know how it goes. I imagine that your best bet is the new Ubuntu subsystem.
