### ISSUE TITLE
how to override default timeout parameters 

### ISSUE THREAD

**Issue by sriramb12** [niklasb/dryscrape#82]
mixins.py has
DEFAULT_WAIT_INTERVAL = 0.5
DEFAULT_WAIT_TIMEOUT = 10
**DEFAULT_AT_TIMEOUT = 1**
need to construct waitMixin with an optional timeout parameter
change in driver code and session needed. will attempt and submit fix

**Comment by niklasb** [comment]
NOTE: This package is not actively maintained. It uses QtWebkit, which is end-of-life and probably doesn't get security fixes backported. Consider using a similar package like Spynner instead.
